/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 25 17:08:41 GMT 2026
 */

package triangle;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import triangle.Triangle;
import triangle.TriangleType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TriangleType_ESTest extends TriangleType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(996, 1091, 927);
      assertEquals(Triangle.SCALENE, triangle0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(721, 721, 1327);
      assertEquals(Triangle.ISOSCELES, triangle0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(1, 2, 1);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(409, 408, 1);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(1, 1, 1077);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(4, 721, 0);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(1077, 0, 3);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(0, 2660, 1621);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(697, 1018, 728);
      assertEquals(Triangle.SCALENE, triangle0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(739, 1288, 1288);
      assertEquals(Triangle.ISOSCELES, triangle0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(306, 306, 1);
      assertEquals(Triangle.ISOSCELES, triangle0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {S
      Triangle triangle0 = TriangleType.triangle(3, 1, 3);
      assertEquals(Triangle.ISOSCELES, triangle0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(1, 782, 1);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(82, 82, 82);
      assertEquals(Triangle.EQUILATERAL, triangle0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(1, 1, 2);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(7249, 1677, 1);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(1358, (-1732), 7249);
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle(1, 1, (-12));
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Triangle triangle0 = TriangleType.triangle((-4978), (-1732), (-220));
      assertEquals(Triangle.INVALID, triangle0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TriangleType triangleType0 = new TriangleType();
  }
}
